

CREATE TABLE IF NOT EXISTS state_tbl (
  id BIGSERIAL PRIMARY KEY,
  state VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS city_tbl (
 id BIGSERIAL PRIMARY KEY,
 city VARCHAR(255),
 state_id INTEGER REFERENCES state_tbl(id),
 food VARCHAR(1024)[] DEFAULT '{}',
 attraction VARCHAR(1024)[] DEFAULT '{}'
 );



 CREATE TABLE units (
id BIGSERIAL PRIMARY KEY,
type VARCHAR (255),
lecture_title VARCHAR(1024),
summary VARCHAR(1024),
gh_url VARCHAR(1024), 
unit INTEGER REFERENCES unit(id),
resources INTEGER REFERENCES res(id),




 CREATE TABLE units (
id BIGSERIAL PRIMARY KEY,
units VARCHAR(50)
);


CREATE TABLE res (
  id BIGSERIAL PRIMARY KEY,

)